agent:
  model: gpt4o-2025-04-25      # pin to dated model
  usd_cap: 5
  repo_prompt: "Fix failing tests"

env:
  docker_image: "foundry_sol:0.4.1"
  post_startup_cmds:
    - ["forge", "test", "-q"]

task:
  branch: fix-demo
  max_attempts: 1

worktrees_dir: .solai/worktrees

backlog:
  file: backlog.yaml 