problem_statement:
  text: "Fix failing tests"

agent:
  model:
    name: gpt-4o-mini
  action_sampler: {}
  usd_cap: 0.20

env:
  repo:
    path: .
  deployment:
    image: foundry_sol:0.4.4

actions:
  open_pr: false
  apply_patch_locally: true 