problem_statement:
  text: "Fix failing tests"

## Required by SWE-agent v1.0.1+ to avoid KeyError: add minimal config fields
trajectory_path: .
run_config: {}

agent:
  model:
    name: gpt-4o-mini
  action_sampler: {}

env:
  repo:
    path: .
  deployment:
    # image: foundry_sol:0.4.5-amd64 # Original static tag
    image: DYNAMIC_IMAGE_TAG_PLACEHOLDER # Placeholder for dynamic replacement

budget:               # ⬅︎ hard cost-cap (supported in SA ≥ 1.2.0)
  usd_cap: 0.20

# usd_cap: 0.20 # Removed - Invalid field for v1.0.1 

keep_container: true

actions:
  open_pr: false
  apply_patch_locally: true