problem_statement:
  text: Fix failing tests

agent:
  model:
    name: gpt-4o-mini

actions:
  apply_patch_locally: true
  open_pr: false

env:
  repo:
    path: .

# budget: <-- Remove 
#   usd_cap: 0.20 <-- Remove

# keep_container: true <-- Remove
