name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install --quiet 'pip-tools==7.4.1' # Pinned version

      - name: Verify Lockfile Consistency
        run: bash .github/scripts/verify-lockfile.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build
      
      - name: Test installation
        run: |
          python -m pip install pipx
          pipx install dist/*.whl
          solai doctor 